export const ErrorMessage = {
  USER_EXIST_ERROR: 'THERE IS A USER WITH THAT EMAIL ALREADY',
  CREATE_USER_ERROR: "COULDN'T CREATE ACCOUNT",
  EDIT_USER_ERROR: "COULDN'T EDIT ACCOUNT",
  HASH_PASSWORD_ERROR: "COULDN'T HASHING PASSWORD",
  LOGIN_ERROR: 'YOUR LOGIN INFORMATION IS INCORRECT',
  USER_NOT_FOUND: 'CAN NOT FIND USER',
  VERIFICATION_NOT_FOUND: 'VERIFICATION NOT FOUND',
  VERIFICATION_ERROR: 'VERIFICATION ERROR',
  RESTAURANT_NOT_FOUND: 'NOT FOUND RESTAURANT',
};
