export const ErrorMessage = {
  USER_EXIST_ERROR: 'THERE IS A USER WITH THAT EMAIL ALREADY',
  CREATE_USER_ERROR: "COULDN'T CREATE ACCOUNT",
  HASH_PASSWORD_ERROR: "COULDN'T HASHING PASSWORD",
  LOGIN_ERROR: 'YOUR LOGIN INFORMATION IS INCORRECT',
};
